# Generated by Django 3.0.2 on 2020-04-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_centerrestaurantmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerrestaurantmapping',
            name='location',
            field=models.CharField(default='Kormangala', max_length=50),
        ),
    ]
